name: Build CirclePopup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          export THEOS=$HOME/theos        # Set THEOS before update
          $THEOS/bin/update-theos         # Now it works

      - name: Build CirclePopup
        run: |
          export THEOS=$HOME/theos
          make -C $PWD clean
          make -C $PWD

      - name: Ad-hoc sign dylib
        run: |
          CIRCLE_DYLIB=$(find ./obj/ -name "*.dylib" | head -n1)
          codesign -s - --force --timestamp=none "$CIRCLE_DYLIB"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CirclePopup.dylib
          path: ./obj/
